USE [master]
GO

/****** Object:  Database [Processos]    Script Date: 24/12/2020 11:42:40 ******/
CREATE DATABASE [Processos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Processos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Processos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Processos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Processos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Processos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Processos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Processos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Processos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Processos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Processos] SET ARITHABORT OFF 
GO

ALTER DATABASE [Processos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Processos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Processos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Processos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Processos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Processos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Processos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Processos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Processos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Processos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Processos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Processos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Processos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Processos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Processos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Processos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Processos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Processos] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Processos] SET  MULTI_USER 
GO

ALTER DATABASE [Processos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Processos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Processos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Processos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Processos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Processos] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Processos] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Processos] SET  READ_WRITE 
GO

